### INDEX
GET http://localhost:3000/products.json


### Suppliers
GET http://localhost:3000/suppliers.json


### SHOW Products
GET http://localhost:3000/products/11.json

### Suppliers
GET http://localhost:3000/suppliers/2.json


### CREATE
# POST http://localhost:3000/products.json
POST https://quiet-anchorage-92191.herokuapp.com/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTA1NjI1NTR9.D6ocWq2bvFQo0L9N5gTVy25cfg6DmmLZoudMsNqwLwg
content-type: application/json

{
	"name": "Cellular Telephone",
  "price": 185.99,
  "description": "Make calls with it, or realistically just text and browse the internet",
  "images": ["https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fshavitech.com%2Fwp-content%2Fuploads%2F2018%2F11%2FCell-Phone-WhatsApp-1-1024x682.jpg", "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fepmgaa.media.clients.ellingtoncms.com%2Fimg%2Fcroppedphotos%2F2013%2F07%2F01%2FS023785885.jpg"],
  "quantity": 7
} 

###
POST http://localhost:3000/suppliers.json
content-type: application/json

{
  "name": "Apple Computer",
  "email": "info@apple.com",
  "phone_number": "555-5555"
}


### UPDATE Product
PATCH https://quiet-anchorage-92191.herokuapp.com/products/9.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTA1NjI1NTR9.D6ocWq2bvFQo0L9N5gTVy25cfg6DmmLZoudMsNqwLwg
content-type: application/json

{
  "new_images": ["https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi5.walmartimages.com%2Fasr%2F642f9f9e-4cf9-475b-a1ba-859c70c233e9_1.6c6bc6a4d17c4ca964b7d81f4f450267.jpeg"]
} 

###
PATCH http://localhost:3000/suppliers/6.json
content-type: application/json

{
  "name": "Microsoft",
  "email": "info@microsoft.net"
}


### DESTROY
DELETE http://localhost:3000/products/16.json

###
DELETE http://localhost:3000/suppliers/6


### CREATE Users

POST http://localhost:3000/users
content-type: application/json

{
  "name": "cleocatra",
  "email": "cleo@cats.com",
  "password": "password",
  "password_confirmation": "password"
}

### CREATE Session
Post https://quiet-anchorage-92191.herokuapp.com/sessions.json
content-type: application/json

{
  "email": "cleo@cats.com",
  "password": "password"
}


### INDEX Order
GET https://quiet-anchorage-92191.herokuapp.com/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTA1NjI1NTR9.D6ocWq2bvFQo0L9N5gTVy25cfg6DmmLZoudMsNqwLwg


### SHOW Order
GET https://quiet-anchorage-92191.herokuapp.com/orders/7.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTA1NjI1NTR9.D6ocWq2bvFQo0L9N5gTVy25cfg6DmmLZoudMsNqwLwg


### INDEX CartedProduct
GET https://quiet-anchorage-92191.herokuapp.com/carted_products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTA1NjI1NTR9.D6ocWq2bvFQo0L9N5gTVy25cfg6DmmLZoudMsNqwLwg

### CREATE CartedProduct
POST http://localhost:3000/carted_products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTA1NjI1NTR9.D6ocWq2bvFQo0L9N5gTVy25cfg6DmmLZoudMsNqwLwg
content-type: application/json

{
  "product_id": 18,
  "quantity": 3
}

###
PATCH https://quiet-anchorage-92191.herokuapp.com/carted?products/7.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NDg1NzAyMjV9.aDJi4souz7F0ltTBtTYC1qQYQNXW7FjaROiAuOKMJMQ
content-type: application/json

{
  "quantity": 2
}

###
POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NDg1NzAyMjV9.aDJi4souz7F0ltTBtTYC1qQYQNXW7FjaROiAuOKMJMQ
