GET http://localhost:3000/first-item

###
GET http://localhost:3000/all-items

###
GET http://localhost:3000/last-item

###
GET http://localhost:3000/lookup-id?id=3

###
GET http://localhost:3000/lookup-id/4

###
GET http://localhost:3000/lookup-name?name=headphones

###
GET http://localhost:3000/lookup-name/headphones