GET http://localhost:3000/products.json

### SHOW
GET http://localhost:3000/products/18.json

### CREATE
POST http://localhost:3000/products.json
content-type: application/json

{
	"name": "Reese's Crunchy Cookie Cup",
  "price": 1,
  "description": "Peanut butter, chocolate cookie, milk chocolate",
  "image_url": "https://i.pinimg.com/originals/00/2f/5e/002f5e8ad34dcbb53bfe4e28a6c7538f.jpg"
} 

###
PATCH http://localhost:3000/products/19.json
content-type: application/json

{
	"name": "Hershey's Chocolate Cup",
  "price": 2
} 

###
DELETE http://localhost:3000/products/19.json
